### ISSUE TITLE
vxe-form-item 折叠表单，按钮“展开/收起”能否自定义文字

### ISSUE THREAD

**Issue by yangxfan** [x-extends/vxe-pc-ui#45]
### 这个需求解决了什么问题：

你好，有个问题咨询一下，`vxe-form-item` 折叠表单，通过 `collapse-node` 字段显示折叠按钮，现在按钮的显示文字是”展开“和”收起“。我们需求是想改成”高级搜索“和”普通搜索“，请问有办法实现吗？现在使用的版本是 `vxe-pc-ui@4.2.24`

### 建议的 API 是什么样的：

希望 `vxe-form-item` 添加属性，例如 `folding-text: '普通搜索'`，`unfolding-text: '高级搜索'`

### 是否已有其他不错的替代方案：

```
<vxe-form-item collapse-node folding-text="普通搜索" unfolding-text="高级搜索">
  <template #default>
    <vxe-button type="submit" status="primary" content="搜索" />
    <vxe-button type="reset" content="重置" />
  </template>
</vxe-form-item>
```

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本。

**Comment by xuliangzhan** [comment]
[新版已支持](https://vxeui.com/#/component/form/config/collapse/buttonText)

**Comment by yangxfan** [comment]
可以了，感谢！
