### ISSUE TITLE
vxe-checkbox 半选状态显示问题

### ISSUE THREAD

**Issue by eng98** [x-extends/vxe-pc-ui#47]
### 可复现的链接（包含复现链接与示例代码）：

https://vxeui.com/v3/#/component/checkbox/indeterminate

### 问题描述与截图：

当 indeterminate 设为true，值为true 时状态不是半选状态，当值为false，indeterminate 值为true时才显示半选，这里优先级是否存在问题
对比 3.8.25 版本则正常

### 操作系统：

window10

### 浏览器版本：

chrome 130.0.6723.59

### vue 版本：

2.7.16

### vxe-pc-ui 版本：

3.1.33

### vxe-table 版本：

3.9.15

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本并已按要求提供复现链接与示例代码。

**Comment by xuliangzhan** [comment]
一直都是这个[逻辑](https://vxeui.com/#/component/checkbox/indeterminate)，如果已选择，则半选无效。如果未选中，则允许半选

**Comment by eng98** [comment]
> 一直都是这个[逻辑](https://vxeui.com/#/component/checkbox/indeterminate)，如果已选择，则半选无效。如果未选中，则允许半选

好的，之前在用3.8版本，看到与3.9版本 半选状态有点不一样所以提了这个问题
