### ISSUE TITLE
校验问题，开启可搜索筛选后，选择相同数据触发校验失败

### ISSUE THREAD

**Issue by kamiponcloud** [x-extends/vxe-pc-ui#58]
### 可复现的链接（包含复现链接与示例代码）：

https://codesandbox.io/p/sandbox/vxe-table-4-x-vue-3-0-wen-ti-yan-shi-forked-zt6687?file=%2Fsrc%2Fviews%2FDemo1.vue%3A17%2C11

### 问题描述与截图：

https://github.com/user-attachments/assets/a719d7b7-3dd9-4a52-ba5e-dc34efc7f50f

当我开启可搜索的时候，选择重复的下拉数据的时候，校验会不通过。

### 期望的结果：

我希望如果有数据的时候可以通过校验

### 操作系统：

win11

### 浏览器版本：

chrome131.0.6778.108

### vue 版本：

3.5.11

### vxe-pc-ui 版本：

4.3.17

### vxe-table 版本：

4.7.87

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本并已按要求提供复现链接与示例代码。

**Comment by kamiponcloud** [comment]
好吧，我设置了trigger: "change"。解决了。但是文档上trigger不是只有change一个值吗？如果有别的值还请说明一下吧

**Comment by xuliangzhan** [comment]
[fix v3.3.18+](https://codesandbox.io/p/sandbox/vxe-table-4-x-vue-3-0-wen-ti-yan-shi-forked-pp7lhc?file=%2Fpackage.json%3A18%2C23&workspaceId=ws_9QgXJxtYGukPm9GZikBvDy)
