### ISSUE TITLE
Grid配置式表格，查询表单插槽方式，官方示例重置不了插槽里面的数据。

### ISSUE THREAD

**Issue by xiaojinrong** [x-extends/vxe-pc-ui#59]
### 可复现的链接（包含复现链接与示例代码）：

https://vxeui.com/#/component/grid/form/itemTemplate

### 问题描述与截图：

![image](https://github.com/user-attachments/assets/0f8d691a-7fb2-4e41-9784-b4de12d99d6e)

### 操作系统：

windows10

### 浏览器版本：

谷歌

### vue 版本：

3.4.27

### vxe-pc-ui 版本：

4.3.14

### vxe-table 版本：

4.9.13

### 是否使用当前最新版本？

- [X] 我已确认是使用当前的最新版本并已按要求提供复现链接与示例代码。

**Comment by xuliangzhan** [comment]
[文档已更新](https://vxeui.com/#/component/grid/form/itemTemplate)
