### ISSUE TITLE
在vxe-grid中编辑表格,数字输入框已经设置已经是integer,但是输入1.5小数后,失去焦点,会发现依旧1.5被保存到了,而不是变为1

### ISSUE THREAD

**Issue by superBiuBiuMan** [x-extends/vxe-pc-ui#6]
### 可复现的链接：

无

### 问题描述与截图：

const gridOptions = reactive<VxeGridProps<RowVO>>({
  border: true,
  editConfig: {
    trigger: 'click',
    mode: 'row'
  },
  columns: [
    { type: 'seq', width: 70 },
    { field: 'name', title: 'Name', width: 200, editRender: { name: 'input' } },
    { field: 'age', title: '数字', width: 200, editRender: { name: 'input', attrs: { type: 'integer' } } },
  ],
  data: [
    { id: 10001, name: 'Test1', role: 'Develop', sex: 'Man', age: 28, date: '', time: '', month: '', week: '', color: '', address: 'test abc' },
    { id: 10002, name: 'Test2', role: 'Test', sex: 'Women', age: 22, date: '', time: '', month: '', week: '', color: '', address: 'Guangzhou' },
    { id: 10003, name: 'Test3', role: 'PM', sex: 'Man', age: 32, date: '2024-06-06', time: '10:30', month: '2024-06', week: '', color: '#571414', address: 'Shanghai' }
  ]
})

### 操作系统：

win11

### 浏览器版本：

chrome

### vue 版本：

最新

### vxe-pc-ui 版本：

4.0.35

### vxe-table 版本：

4.7.36

**Comment by xlz26296** [comment]
你这个是用的原生 input，你应该使用 [vxe-input](https://vxetable.cn/#/component/grid/editTemplate/vxe-input) 才有这个功能

**Comment by superBiuBiuMan** [comment]
> 你这个是用的原生 input，你应该使用 [vxe-input](https://vxetable.cn/#/component/grid/editTemplate/vxe-input) 才有这个功能

好吧,原来是这个问题~
